const express = require("express");
const jobRouter = express.Router();
const getJobs = require("./controller/getJobs");
const getJobById = require("./controller/getJobById");
const hire = require("./controller/hire");
const completeJob = require("./controller/completedJob");
jobRouter.get("/", getJobs);
jobRouter.get("/getJobById/:id", getJobById);
jobRouter.post("/hire/:applicationId", hire);
jobRouter.post("/completeJob/:jobId", completeJob);
module.exports = jobRouter;
